# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-03-27 14:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerInformation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=120)),
                ('last_name', models.CharField(max_length=120)),
                ('title', models.CharField(blank=True, max_length=120, null=True)),
                ('phone', models.CharField(max_length=13)),
                ('email', models.EmailField(max_length=254)),
                ('company_name', models.CharField(max_length=120)),
                ('street', models.CharField(max_length=120)),
                ('city', models.CharField(max_length=120)),
                ('state', models.CharField(max_length=120)),
                ('zipcode', models.CharField(max_length=120)),
                ('country', models.CharField(max_length=120)),
                ('website', models.CharField(blank=True, max_length=120, null=True)),
                ('deal_size', models.DecimalField(decimal_places=2, max_digits=50)),
            ],
        ),
    ]
