# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-03-27 16:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stage', models.CharField(choices=[('initial', 'Initial'), ('qualification', 'Qualification'), ('presentation', 'Presentation'), ('evaluation', 'Evaluation'), ('closing', 'Closing')], default='Initial', max_length=120)),
                ('deal_size', models.DecimalField(blank=True, decimal_places=2, max_digits=50, null=True)),
                ('to_do_task', models.CharField(blank=True, max_length=120, null=True)),
                ('to_do_date', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='customerinformation',
            name='deal_size',
        ),
        migrations.AddField(
            model_name='customerstatus',
            name='company_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customer.CustomerInformation'),
        ),
    ]
