# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-05-04 03:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companydetails',
            name='phone_no_1',
            field=models.IntegerField(max_length=13),
        ),
        migrations.AlterField(
            model_name='companydetails',
            name='phone_no_2',
            field=models.IntegerField(blank=True, max_length=13, null=True),
        ),
    ]
