# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-03-28 04:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0002_auto_20180327_1642'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customerstatus',
            old_name='to_do_date',
            new_name='follow_up_date',
        ),
        migrations.RenameField(
            model_name='customerstatus',
            old_name='to_do_task',
            new_name='follow_up_task',
        ),
        migrations.AddField(
            model_name='customerinformation',
            name='created',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='customerinformation',
            name='updated',
            field=models.DateField(auto_now=True),
        ),
    ]
