# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-05-04 03:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0002_auto_20180504_0326'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companydetails',
            name='phone_no_1',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='companydetails',
            name='phone_no_2',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
