# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-05-04 03:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0004_auto_20180504_0344'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companydetails',
            name='slug',
            field=models.SlugField(editable=False, unique=True),
        ),
    ]
