# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-05-15 05:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0006_auto_20180507_0250'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='task_status',
            field=models.IntegerField(default=0),
        ),
    ]
