# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-05-16 06:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0007_auto_20180515_0547'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='task_status',
            field=models.IntegerField(choices=[(0, 'Pending'), (1, 'Completed'), (3, 'Failed')], default=0),
        ),
    ]
