# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-05-18 03:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0008_auto_20180516_0640'),
    ]

    operations = [
        migrations.RenameField(
            model_name='companydetails',
            old_name='added_by',
            new_name='account_owner',
        ),
        migrations.RemoveField(
            model_name='companydetails',
            name='phone_no_1',
        ),
        migrations.RemoveField(
            model_name='companydetails',
            name='phone_no_2',
        ),
        migrations.AddField(
            model_name='companydetails',
            name='company_owner',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='companydetails',
            name='industry_type',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='companydetails',
            name='no_of_employee',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='companydetails',
            name='phone',
            field=models.BigIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='companydetails',
            name='revenue',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='task_status',
            field=models.IntegerField(choices=[(0, 'Pending'), (1, 'Completed'), (2, 'Failed')], default=0),
        ),
    ]
