# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-03-29 09:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('Superuser', 'Superuser'), ('Manager', 'Manager'), ('Salesman', 'Salesman')], max_length=40),
        ),
    ]
